### ISSUE TITLE
1.7.x client crash (metadata issue)

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaRewind#174]
Crash GAME: The game crashed whilst ticking entity Error: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte

[14:45:03 WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x33->0x33
[14:45:03 WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x33->0x33
[14:45:03 WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x33->0x33
[14:45:03 WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x33->0x33
[14:45:03 WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x33->0x33

PaperSpigot: 1.12.2 (latest)
ViaRewind Build - request -> 48

**Comment by Gerrygames** [comment]
Can you provide the client crash report? It's located in .minecraft/crash-reports/

**Comment by Incluuu** [comment]
this error is still dependent by the sign

**Comment by Gerrygames** [comment]
Did you update to https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/48/?

**Comment by Gerrygames** [comment]
The issue with signs got fixed in https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/48/. To fix the client crash I need the client crash report.

**Comment by Incluuu** [comment]
I used this version, but the problem with: "ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x33-> 0x33" still appears in the console.

**Comment by KennyTV** [comment]
**_To fix the client crash I need the client crash report._**
Also, update VV to https://ci.viaversion.com/job/ViaVersion/ and send your `/viaver dump` output afterwards

**Comment by Incluuu** [comment]
crash report: https://pastebin.com/vXs1QHUi

**Comment by xion87** [comment]
i got a similiar issue to your error maybe is related? 
https://github.com/ViaVersion/ViaBackwards/issues/222
There is no client crash error, just "proxy disconected", something that bungee don't like

**Comment by LoXR** [comment]
Getting the same on my 1.13.2 hubs, when a player join on 1.7 it'll immediately crash the hub.
Dump: https://dump.viaversion.com/ca6af5b401c3dc308a56aa6089b13ceb6a006e7cd1f930d777355c45aab06092
Error: https://mcpaste.io/abf5dd93136d7bcf

**Comment by Gerrygames** [comment]
@Incluuu the paste is no longer available.
@xion87 @LoXR Both of your issues have nothing to do with this one. Updating all your Via* plugins to the latest dev builds from https://ci.viaversion.com/ should fix them.

**Comment by LoXR** [comment]
I am on the latest of all, using the -DEV for ViaVersion & ViaRewind, while having the latest for ViaBackwards.

**Comment by Gerrygames** [comment]
You probably need ViaBackwards dev too.

**Comment by LoXR** [comment]
Seems the same error: https://mcpaste.io/9136e244d211adb2, this time it actually doesnt crash but will constantly diasconnect me upon joining.

**Comment by LoXR** [comment]
For my side of the issue, I've managed to fix the 1.7 crash just be redownloading all the Via's from Spigot.
